# This is example config

[database]
driver = "postgres"
url  = "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=vcms sslmode=disable"

# mysql
# driver = "mysql"
# url  = "root:b2c456@(172.26.62.50:3306)/vcms?parseTime=True"

[http]
host = "0.0.0.0"
port = 8080


