# This is example config

[database]
#driver = "postgres"
#url  = "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=vcms sslmode=disable"

# sqlite3
driver = "sqlite3"
url  = "./vcms.db"

[http]
host = "0.0.0.0"
port = 8080


